"""Single-output sklearn decision trees, exactly three integer-scaled features only."""
import hashlib
import json
import math
import platform
from pathlib import Path
import numpy as np
import sklearn

FEATURES = ['light', 'temperature', 'humidity']
MODEL_FEATURES = ['light_raw', 'temperature_x10', 'humidity_x10']
PREPROCESS = 'raw-int,tenth-int,tenth-int-v1'

def features_for_model(frame):
    out = frame[FEATURES].copy()
    out['light'] = out['light'].astype(int)
    for name in FEATURES[1:]:
        out[name] = out[name].map(lambda x: int(round(float(x)*10)))
    out.columns = MODEL_FEATURES
    return out

def export_pico_model(clf, ranges=None):
    if clf.n_outputs_ != 1 or clf.n_features_in_ != 3:
        raise ValueError('Only single-output, three-feature classifiers are supported')
    if hasattr(clf, 'feature_names_in_') and list(clf.feature_names_in_) != MODEL_FEATURES:
        raise ValueError('Unexpected feature order')
    if clf.get_depth() > 3:
        raise ValueError('Course model depth must be <= 3')
    tree = clf.tree_
    lines = ['# Automatically generated from fitted model.tree_. Do not edit thresholds.',
             'FEATURES = '+repr(tuple(FEATURES)), 'PREPROCESS = '+repr(PREPROCESS),
             'TRAINING_RANGES = '+repr(ranges),
             'def predict(light, temperature, humidity):',
             '    light_raw = int(light)',
             '    temperature_x10 = int(round(temperature * 10))',
             '    humidity_x10 = int(round(humidity * 10))']
    def walk(node, depth):
        pad = '    '*depth
        left, right = int(tree.children_left[node]), int(tree.children_right[node])
        if left == right:
            label = str(clf.classes_[int(np.argmax(tree.value[node][0]))])
            lines.append(pad+'return '+repr(label))
            return
        feature = MODEL_FEATURES[int(tree.feature[node])]
        cut = math.floor(float(tree.threshold[node]))
        lines.append(pad+f'if {feature} <= {cut}:')
        walk(left, depth+1)
        lines.append(pad+'else:')
        walk(right, depth+1)
    walk(0, 1)
    body = '\n'.join(lines)+'\n'
    model_id = 'dt-'+hashlib.sha256(body.encode()).hexdigest()[:12]
    return 'MODEL_ID = '+repr(model_id)+'\n'+body, model_id

def boundary_probes(clf, domain=((0,65535),(0,500),(0,1000))):
    """Visit each split with all ancestor path constraints; never test unreachable probes."""
    probes = []
    tree = clf.tree_
    def visit(node, bounds):
        left, right = int(tree.children_left[node]), int(tree.children_right[node])
        if left == right:
            return
        feature = int(tree.feature[node]); cut = math.floor(float(tree.threshold[node]))
        for value in (cut-1, cut, cut+1):
            if bounds[feature][0] <= value <= bounds[feature][1]:
                point = [(lo+hi)//2 for lo,hi in bounds]
                point[feature] = value
                probes.append(point)
        for child, is_left in ((left,True),(right,False)):
            next_bounds = list(bounds)
            lo, hi = bounds[feature]
            next_bounds[feature] = (lo,min(hi,cut)) if is_left else (max(lo,cut+1),hi)
            if all(a<=b for a,b in next_bounds):
                visit(child,next_bounds)
    visit(0,list(domain))
    return probes

def validate_conversion(clf, source, raw_rows, domain=((0,65535),(0,500),(0,1000))):
    # Execute only source generated by export_pico_model in this process.
    namespace = {}
    exec(compile(source, '<generated-classroom-model>', 'exec'), namespace)
    rng = np.random.default_rng(42)
    synthetic = np.column_stack([rng.integers(lo, hi+1, 1000) for lo,hi in domain]).tolist()
    probes = boundary_probes(clf, domain)
    real = [[int(l),int(round(t*10)),int(round(h*10))] for l,t,h in raw_rows]
    scaled = real+synthetic+probes
    # Inputs only; fixtures never enter fit or measured accuracy.
    import pandas as pd
    expected = clf.predict(pd.DataFrame(scaled, columns=MODEL_FEATURES) if hasattr(clf,'feature_names_in_') else np.array(scaled))
    tests = []
    for point,label in zip(scaled,expected):
        values = [point[0],point[1]/10,point[2]/10]
        actual = namespace['predict'](*values)
        if actual != label:
            raise AssertionError((values,label,actual))
        tests.append({'input':values,'expected':str(label)})
    return tests

def write_artifacts(clf, train, test, csv_hashes, metrics, directory='.'):
    ranges = [(float(train[f].min()),float(train[f].max())) for f in FEATURES]
    source, model_id = export_pico_model(clf, ranges)
    raw_rows = list(train[FEATURES].itertuples(index=False,name=None))+list(test[FEATURES].itertuples(index=False,name=None))
    tests = validate_conversion(clf,source,raw_rows)
    metadata = dict(model_id=model_id, source_sha256=hashlib.sha256(source.encode()).hexdigest(),
        features=FEATURES, units=['raw','C','%RH'], preprocess=PREPROCESS,
        classes=[str(c) for c in clf.classes_], max_depth=clf.max_depth,
        min_samples_leaf=clf.min_samples_leaf, random_state=clf.random_state,
        train_count=len(train), test_count=len(test),
        train_class_counts={str(k):int(v) for k,v in train.label.value_counts().items()},
        test_class_counts={str(k):int(v) for k,v in test.label.value_counts().items()},
        train_sessions=sorted(train.session_id.unique()),test_sessions=sorted(test.session_id.unique()),
        csv_sha256=csv_hashes, python=platform.python_version(),sklearn=sklearn.__version__,numpy=np.__version__,
        metrics=metrics,training_ranges=dict(zip(FEATURES,ranges)),hardware_status='NOT_RUN')
    out = Path(directory); out.mkdir(parents=True,exist_ok=True)
    (out/'model.py').write_bytes(source.encode('utf-8'))  # Preserve the hashed LF bytes on Windows too.
    (out/'model-meta.json').write_text(json.dumps(metadata,ensure_ascii=False,indent=2),encoding='utf-8')
    (out/'model-tests.json').write_text(json.dumps({'model_id':model_id,'tests':tests},ensure_ascii=False),encoding='utf-8')
    return metadata
