export type ArduinoLesson = {
  id: number;
  shortTitle: string;
  title: string;
  subtitle: string;
  duration: string;
  input: string;
  output: string;
  objectives: string[];
  concepts: { title: string; body: string; exam: string }[];
  parts: string[];
  wiring: { from: string; to: string; note: string }[];
  simulatorUrl: string;
  simulatorNote: string;
  steps: string[];
  code: string;
  lineNotes: { code: string; meaning: string }[];
  expected: string;
  challenge: string;
  errors: { symptom: string; cause: string; fix: string }[];
  quiz: { question: string; options: string[]; answer: number; explanation: string };
  examPrompts: { type: string; prompt: string }[];
  teacher: string;
};

export const arduinoLessons: ArduinoLesson[] = [
  {
    id: 1,
    shortTitle: "LED·저항",
    title: "LED와 저항으로 디지털 출력 이해하기",
    subtitle: "HIGH와 LOW가 실제 빛의 켜짐과 꺼짐으로 바뀌는 과정을 확인합니다.",
    duration: "핵심 20분",
    input: "시간과 프로그램 명령",
    output: "LED 켜기·끄기",
    objectives: [
      "LED의 애노드와 캐소드를 구분할 수 있다.",
      "저항이 필요한 이유를 전류 제한과 연결해 설명할 수 있다.",
      "pinMode(), digitalWrite(), delay()의 역할을 해석할 수 있다.",
    ],
    concepts: [
      { title: "디지털 출력", body: "Arduino 핀이 HIGH일 때 약 5V, LOW일 때 약 0V 상태가 되어 두 상태를 구분해 출력합니다.", exam: "HIGH·LOW의 전압 상태와 LED 동작을 연결해 출제할 수 있습니다." },
      { title: "LED 극성", body: "긴 다리인 애노드는 + 쪽, 짧은 다리인 캐소드는 GND 쪽으로 연결합니다.", exam: "LED 방향을 반대로 연결했을 때의 결과를 묻습니다." },
      { title: "전류 제한 저항", body: "220Ω 저항은 LED로 흐르는 전류가 지나치게 커지지 않도록 제한해 LED와 보드를 보호합니다.", exam: "저항의 위치보다 직렬 연결과 전류 제한 역할이 핵심입니다." },
      { title: "순차 구조", body: "켜기→기다리기→끄기→기다리기 명령이 위에서 아래로 실행되고 loop()에서 반복됩니다.", exam: "코드를 보고 한 주기의 시간과 동작 순서를 계산합니다." },
    ],
    parts: ["Arduino Uno R3", "브레드보드", "LED", "220Ω 저항", "점퍼선"],
    wiring: [
      { from: "Arduino D9", to: "220Ω 저항 한쪽", note: "D9를 디지털 출력으로 사용" },
      { from: "저항 다른 쪽", to: "LED 애노드(긴 다리)", note: "저항과 LED를 직렬 연결" },
      { from: "LED 캐소드(짧은 다리)", to: "Arduino GND", note: "전류가 돌아오는 경로" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "공개 LED 회로를 참고하되 핀 번호와 코드는 이 교재의 D9·220Ω 기준으로 구성합니다.",
    steps: [
      "Tinkercad Circuits에서 Arduino Uno와 브레드보드를 놓는다.",
      "D9→220Ω 저항→LED 애노드, LED 캐소드→GND 순서로 연결한다.",
      "코드 보기에서 텍스트 모드로 바꾸고 전체 코드를 붙여 넣는다.",
      "시뮬레이션 시작 전 LED가 몇 초 간격으로 깜빡일지 예측한다.",
      "delay 값을 500에서 100으로 바꾸고 한 주기의 시간을 비교한다.",
    ],
    code: [
      "const int LED_PIN = 9;",
      "",
      "void setup() {",
      "  pinMode(LED_PIN, OUTPUT);",
      "}",
      "",
      "void loop() {",
      "  digitalWrite(LED_PIN, HIGH);",
      "  delay(500);",
      "  digitalWrite(LED_PIN, LOW);",
      "  delay(500);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "const int LED_PIN = 9;", meaning: "LED가 연결된 9번 핀을 바뀌지 않는 상수로 저장합니다." },
      { code: "pinMode(LED_PIN, OUTPUT);", meaning: "9번 핀을 전기 신호를 내보내는 출력 모드로 설정합니다." },
      { code: "digitalWrite(..., HIGH);", meaning: "핀을 HIGH 상태로 만들어 LED를 켭니다." },
      { code: "delay(500);", meaning: "500ms, 즉 0.5초 동안 다음 명령으로 넘어가지 않습니다." },
      { code: "digitalWrite(..., LOW);", meaning: "핀을 LOW 상태로 만들어 LED를 끕니다." },
    ],
    expected: "LED가 0.5초 켜지고 0.5초 꺼지는 동작을 계속 반복합니다. 한 주기는 1초입니다.",
    challenge: "LED를 0.1초 간격으로 두 번 깜빡인 뒤 1초 쉬게 코드를 수정하세요.",
    errors: [
      { symptom: "LED가 켜지지 않음", cause: "LED 방향이 반대이거나 GND가 끊김", fix: "애노드·캐소드와 전류 경로를 다시 확인" },
      { symptom: "LED가 손상되거나 과전류 경고", cause: "저항을 빼고 직접 연결함", fix: "220Ω 저항을 LED와 직렬로 연결" },
    ],
    quiz: {
      question: "LED와 220Ω 저항을 직렬로 연결하는 가장 중요한 이유는?",
      options: ["LED 색을 바꾸기 위해", "전류를 제한해 LED와 보드를 보호하기 위해", "핀 번호를 저장하기 위해", "반복 속도를 높이기 위해"],
      answer: 1,
      explanation: "저항은 전류를 제한합니다. digitalWrite나 delay의 실행 속도를 조절하는 부품이 아닙니다.",
    },
    examPrompts: [
      { type: "코드 추적", prompt: "delay(300)이 두 번 사용되면 LED 깜빡임 한 주기는 몇 초인지 계산하시오." },
      { type: "회로 진단", prompt: "LED의 긴 다리를 GND에 연결했을 때 예상되는 결과와 원인을 쓰시오." },
      { type: "서술형", prompt: "센서가 없는 이 회로에서도 입력·처리·출력을 구분하여 설명하시오." },
    ],
    teacher: "LED를 먼저 켜지 말고 회로에서 전류가 D9→저항→LED→GND로 흐르는 경로를 손가락으로 짚게 합니다.",
  },
  {
    id: 2,
    shortTitle: "초음파",
    title: "초음파 센서로 거리를 측정하고 경고하기",
    subtitle: "왕복 시간으로 거리를 계산하고 가까운 물체를 빛과 소리로 알립니다.",
    duration: "핵심 25분",
    input: "HC-SR04 거리",
    output: "LED·피에조 부저",
    objectives: [
      "TRIG와 ECHO 핀의 역할을 구분할 수 있다.",
      "초음파 왕복 시간으로 거리를 계산하는 식을 설명할 수 있다.",
      "임계값 조건에 따라 LED와 부저를 제어할 수 있다.",
    ],
    concepts: [
      { title: "TRIG", body: "10μs의 짧은 신호를 보내 센서가 초음파를 발생하게 합니다.", exam: "digitalWrite와 delayMicroseconds의 순서를 묻습니다." },
      { title: "ECHO", body: "초음파가 물체에 반사되어 돌아올 때까지 HIGH로 유지된 시간을 pulseIn()으로 측정합니다.", exam: "pulseIn()의 반환값이 거리 자체가 아니라 시간임을 구분합니다." },
      { title: "거리 계산", body: "거리(cm)=왕복 시간(μs)×0.0343÷2입니다. 0.0343cm/μs는 공기 중 소리의 속도에 해당합니다.", exam: "왕복이므로 2로 나누는 이유를 서술하게 합니다." },
      { title: "임계값", body: "측정 거리가 20cm보다 작을 때 경고하도록 조건을 정합니다.", exam: "<, <=와 임계값 변경에 따른 결과를 묻습니다." },
    ],
    parts: ["Arduino Uno R3", "HC-SR04", "LED", "220Ω 저항", "피에조 부저", "점퍼선"],
    wiring: [
      { from: "HC-SR04 VCC / GND", to: "5V / GND", note: "전원과 공통 접지" },
      { from: "HC-SR04 TRIG", to: "D7", note: "Arduino가 시작 신호 출력" },
      { from: "HC-SR04 ECHO", to: "D6", note: "왕복 시간 입력" },
      { from: "LED 애노드", to: "D9를 거쳐 220Ω", note: "경고 빛 출력" },
      { from: "피에조 +", to: "D10", note: "경고음 출력, 다른 쪽은 GND" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "초음파·LED·부저 공개 회로를 참고하고, 아래 연결표와 20cm 임계값 코드를 기준으로 실습합니다.",
    steps: [
      "HC-SR04의 VCC·TRIG·ECHO·GND 글자를 확대해 확인한다.",
      "연결표에 따라 센서·LED·부저를 연결한다.",
      "시뮬레이션을 시작하고 초음파 센서를 클릭해 가상 물체 거리를 바꾼다.",
      "20cm 전후에서 LED와 부저가 어떻게 변하는지 기록한다.",
      "임계값을 20에서 40으로 수정하고 조건이 바뀐 범위를 설명한다.",
    ],
    code: [
      "const int TRIG_PIN = 7;",
      "const int ECHO_PIN = 6;",
      "const int LED_PIN = 9;",
      "const int BUZZER_PIN = 10;",
      "",
      "void setup() {",
      "  pinMode(TRIG_PIN, OUTPUT);",
      "  pinMode(ECHO_PIN, INPUT);",
      "  pinMode(LED_PIN, OUTPUT);",
      "  Serial.begin(9600);",
      "}",
      "",
      "void loop() {",
      "  digitalWrite(TRIG_PIN, LOW);",
      "  delayMicroseconds(2);",
      "  digitalWrite(TRIG_PIN, HIGH);",
      "  delayMicroseconds(10);",
      "  digitalWrite(TRIG_PIN, LOW);",
      "",
      "  unsigned long duration = pulseIn(ECHO_PIN, HIGH, 30000UL);",
      "  float distanceCm = duration * 0.0343 / 2.0;",
      "  Serial.println(distanceCm);",
      "",
      "  if (duration > 0 && distanceCm < 20.0) {",
      "    digitalWrite(LED_PIN, HIGH);",
      "    tone(BUZZER_PIN, 880);",
      "  } else {",
      "    digitalWrite(LED_PIN, LOW);",
      "    noTone(BUZZER_PIN);",
      "  }",
      "  delay(100);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "delayMicroseconds(10);", meaning: "TRIG를 10μs 동안 HIGH로 유지해 측정을 시작합니다." },
      { code: "pulseIn(ECHO_PIN, HIGH, 30000UL)", meaning: "ECHO가 HIGH인 왕복 시간을 측정하며 30,000μs 후에는 기다림을 끝냅니다." },
      { code: "duration * 0.0343 / 2.0", meaning: "시간×소리의 속도로 왕복 거리를 구한 뒤 2로 나눠 편도 거리를 구합니다." },
      { code: "distanceCm < 20.0", meaning: "물체가 20cm보다 가까울 때만 경고를 출력합니다." },
      { code: "tone(..., 880)", meaning: "피에조 부저에 880Hz 사각파를 출력해 소리를 냅니다." },
    ],
    expected: "물체가 20cm 안으로 들어오면 LED가 켜지고 부저가 울리며, 멀어지면 두 출력이 꺼집니다.",
    challenge: "거리가 10cm 미만이면 1200Hz, 10~30cm이면 600Hz가 나도록 조건을 두 단계로 나누세요.",
    errors: [
      { symptom: "거리가 항상 0", cause: "TRIG·ECHO를 바꾸어 연결했거나 시간 초과", fix: "센서 글자와 D7·D6 연결을 다시 확인" },
      { symptom: "거리가 실제의 약 두 배", cause: "왕복 시간을 2로 나누지 않음", fix: "거리 계산식 끝에 / 2.0 추가" },
    ],
    quiz: {
      question: "초음파 거리 계산식에서 측정 시간을 2로 나누는 이유는?",
      options: ["센서가 두 개이기 때문에", "초음파가 물체까지 갔다가 돌아오는 왕복 시간을 측정하기 때문에", "TRIG가 2μs이기 때문에", "Arduino가 2바이트를 사용하기 때문에"],
      answer: 1,
      explanation: "ECHO 시간은 센서→물체→센서의 왕복 시간입니다. 우리가 필요한 것은 센서에서 물체까지의 편도 거리입니다.",
    },
    examPrompts: [
      { type: "계산형", prompt: "왕복 시간이 1,000μs일 때 물체까지의 거리를 계산하시오. 소리의 속도는 0.0343cm/μs로 한다." },
      { type: "코드 해석", prompt: "distanceCm < 20.0을 distanceCm <= 30.0으로 바꾸면 출력 조건이 어떻게 달라지는지 쓰시오." },
      { type: "오류 진단", prompt: "거리값이 계속 0일 때 전원→GND→핀→코드 순서로 점검 항목을 제시하시오." },
    ],
    teacher: "학생이 0.0343이라는 수를 외우는 것보다 pulseIn이 시간을 측정하고, 왕복이므로 2로 나눈다는 구조를 설명하게 합니다.",
  },
  {
    id: 3,
    shortTitle: "온습도",
    title: "DHT11로 온도·습도를 읽고 환경을 알리기",
    subtitle: "하나의 디지털 센서가 두 측정값을 전달하고 조건에 따라 경고를 출력합니다.",
    duration: "핵심 25분",
    input: "온도·습도",
    output: "빨강/초록 LED·부저",
    objectives: [
      "DHT11이 온도와 습도를 디지털 데이터로 전달함을 설명할 수 있다.",
      "라이브러리와 객체의 역할을 구분할 수 있다.",
      "복합 조건 ||를 이용해 환경 경고를 만들 수 있다.",
    ],
    concepts: [
      { title: "디지털 센서", body: "DHT11 내부에서 측정값을 디지털 데이터로 만들어 DATA 한 가닥으로 전달합니다.", exam: "조도센서의 analogRead와 DHT11의 라이브러리 읽기를 비교합니다." },
      { title: "라이브러리", body: "DHT.h는 센서 통신의 복잡한 시간 처리를 함수로 제공해 dht.readTemperature()처럼 사용할 수 있게 합니다.", exam: "#include와 객체 생성문의 역할을 구분합니다." },
      { title: "복합 조건", body: "||는 둘 중 하나만 참이어도 전체 조건이 참이고, &&는 두 조건이 모두 참일 때 참입니다.", exam: "온도·습도 조건의 참/거짓을 표로 분석합니다." },
      { title: "결측값", body: "센서 통신 실패 시 NaN이 나올 수 있어 isnan()으로 검사한 뒤 출력을 결정합니다.", exam: "오류값을 정상값처럼 제어에 사용하면 안 되는 이유를 묻습니다." },
    ],
    parts: ["Arduino Uno R3", "DHT11", "LED 2개", "220Ω 저항 2개", "피에조 부저", "점퍼선"],
    wiring: [
      { from: "DHT11 VCC / GND", to: "5V / GND", note: "모듈 표기의 +·- 확인" },
      { from: "DHT11 DATA", to: "D2", note: "디지털 온습도 데이터" },
      { from: "빨강 LED / 초록 LED", to: "D9 / D8", note: "각 LED에 220Ω 직렬 저항" },
      { from: "피에조 +", to: "D10", note: "환경 경고음, 다른 쪽은 GND" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "DHT11 공개 회로를 참고합니다. 계정·회로 환경에 따라 DHT 라이브러리 사용 여부가 다르면 교사의 기준 회로를 우선합니다.",
    steps: [
      "DHT11의 VCC·DATA·GND 방향을 확인하고 D2에 DATA를 연결한다.",
      "LED 두 개와 부저를 연결한 뒤 전체 코드를 입력한다.",
      "시리얼 모니터를 열고 온도와 습도 값을 확인한다.",
      "가상 센서 값을 바꾸어 28℃ 또는 70% 조건을 통과시킨다.",
      "||를 &&로 바꾸었을 때 경고가 울리는 경우를 비교한다.",
    ],
    code: [
      "#include <DHT.h>",
      "",
      "const int DHT_PIN = 2;",
      "const int RED_LED = 9;",
      "const int GREEN_LED = 8;",
      "const int BUZZER_PIN = 10;",
      "DHT dht(DHT_PIN, DHT11);",
      "",
      "void setup() {",
      "  pinMode(RED_LED, OUTPUT);",
      "  pinMode(GREEN_LED, OUTPUT);",
      "  Serial.begin(9600);",
      "  dht.begin();",
      "}",
      "",
      "void loop() {",
      "  float humidity = dht.readHumidity();",
      "  float temperature = dht.readTemperature();",
      "",
      "  if (isnan(humidity) || isnan(temperature)) {",
      "    Serial.println(\"DHT11 read error\");",
      "    delay(2000);",
      "    return;",
      "  }",
      "",
      "  Serial.print(temperature);",
      "  Serial.print(\" C, \" );",
      "  Serial.print(humidity);",
      "  Serial.println(\" %\");",
      "",
      "  if (temperature >= 28.0 || humidity >= 70.0) {",
      "    digitalWrite(RED_LED, HIGH);",
      "    digitalWrite(GREEN_LED, LOW);",
      "    tone(BUZZER_PIN, 660, 200);",
      "  } else {",
      "    digitalWrite(RED_LED, LOW);",
      "    digitalWrite(GREEN_LED, HIGH);",
      "    noTone(BUZZER_PIN);",
      "  }",
      "  delay(2000);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "#include <DHT.h>", meaning: "DHT 센서 통신 함수가 들어 있는 라이브러리를 불러옵니다." },
      { code: "DHT dht(DHT_PIN, DHT11);", meaning: "D2에 연결된 DHT11을 dht라는 객체로 만듭니다." },
      { code: "dht.readHumidity()", meaning: "습도를 % 단위의 실수로 읽습니다." },
      { code: "isnan(...) || isnan(...)", meaning: "두 값 중 하나라도 숫자가 아니면 정상 제어를 중단합니다." },
      { code: "temperature >= 28.0 || humidity >= 70.0", meaning: "온도 또는 습도 중 하나라도 기준 이상이면 경고합니다." },
    ],
    expected: "온도 28℃ 이상 또는 습도 70% 이상이면 빨강 LED와 경고음이 나오고, 그 외에는 초록 LED가 켜집니다.",
    challenge: "온도만 높을 때, 습도만 높을 때, 둘 다 높을 때 서로 다른 음높이가 나도록 조건을 세 단계로 나누세요.",
    errors: [
      { symptom: "DHT11 read error 반복", cause: "DATA 핀·센서 종류·읽기 주기 문제", fix: "D2 연결과 DHT11 선언을 확인하고 2초 이상 간격 유지" },
      { symptom: "온도와 습도는 나오지만 LED가 반대", cause: "LED 핀 또는 HIGH·LOW 순서가 바뀜", fix: "D9 빨강·D8 초록 연결과 조건문 확인" },
    ],
    quiz: {
      question: "조건 temperature >= 28 || humidity >= 70이 참이 되는 경우는?",
      options: ["두 값이 모두 기준 미만일 때", "온도와 습도가 모두 기준 이상일 때만", "둘 중 하나 이상이 기준 이상일 때", "센서값이 NaN일 때만"],
      answer: 2,
      explanation: "||는 OR 연산자이므로 둘 중 하나만 참이어도 전체 조건은 참입니다.",
    },
    examPrompts: [
      { type: "논리식", prompt: "온도와 습도가 모두 기준 이상일 때만 경고하려면 조건식을 어떻게 바꾸어야 하는지 쓰시오." },
      { type: "코드 해석", prompt: "return이 실행되면 그 아래 LED 제어문이 실행되지 않는 이유를 설명하시오." },
      { type: "비교형", prompt: "DHT11과 조도센서가 값을 Arduino에 전달하는 방식의 차이를 설명하시오." },
    ],
    teacher: "DHT11은 측정 주기가 느립니다. 값이 바로 변하지 않는 것을 오류로 단정하지 말고 2초 간격과 디지털 통신 특성을 함께 설명합니다.",
  },
  {
    id: 4,
    shortTitle: "조도·PWM",
    title: "조도센서의 아날로그 입력과 PWM 밝기 출력",
    subtitle: "0~1023의 빛 값을 0~255의 LED 밝기로 변환합니다.",
    duration: "핵심 25분",
    input: "LDR 조도 0~1023",
    output: "PWM LED 0~255",
    objectives: [
      "전압 분배 회로가 조도 변화를 전압으로 바꾸는 원리를 설명할 수 있다.",
      "10비트 ADC와 8비트 PWM의 값 범위를 구분할 수 있다.",
      "map()으로 입력 범위를 출력 범위로 변환할 수 있다.",
    ],
    concepts: [
      { title: "전압 분배", body: "LDR과 10kΩ 저항을 직렬로 연결하고 중간 전압을 A0에서 읽습니다. 밝아질수록 LDR 저항이 작아져 이 배선에서는 A0 전압이 커집니다.", exam: "LDR 위치가 바뀌면 값의 증가 방향도 바뀔 수 있음을 묻습니다." },
      { title: "ADC 10비트", body: "Arduino Uno는 0~5V 입력을 2¹⁰=1024단계, 숫자 0~1023으로 변환합니다.", exam: "단계 수와 최댓값을 구분합니다." },
      { title: "PWM 8비트", body: "analogWrite()는 0~255의 256단계 듀티비로 매우 빠르게 켜고 꺼 평균 밝기를 조절합니다.", exam: "PWM이 진짜 연속 전압 출력이 아님을 묻습니다." },
      { title: "map()", body: "map(lightValue, 0, 1023, 0, 255)는 ADC 범위를 PWM 범위로 비례 변환합니다.", exam: "입력값 변화에 따른 출력값을 계산합니다." },
    ],
    parts: ["Arduino Uno R3", "LDR", "10kΩ 저항", "LED", "220Ω 저항", "점퍼선"],
    wiring: [
      { from: "5V", to: "LDR 한쪽", note: "빛에 따라 저항이 변함" },
      { from: "LDR 다른 쪽", to: "A0와 10kΩ 한쪽", note: "전압 분배의 중간 지점" },
      { from: "10kΩ 다른 쪽", to: "GND", note: "전압 분배 완성" },
      { from: "D9(~)", to: "220Ω→LED 애노드", note: "PWM 핀 사용, LED 캐소드는 GND" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "LDR와 LED 밝기 제어 공개 예제를 참고합니다. A0 전압 분배 방향과 D9 PWM 연결은 아래 표를 기준으로 맞춥니다.",
    steps: [
      "LDR와 10kΩ 저항으로 전압 분배 회로를 만들고 중간점을 A0에 연결한다.",
      "PWM 표시가 있는 D9에 LED와 220Ω 저항을 연결한다.",
      "시뮬레이션에서 LDR를 클릭해 빛의 세기를 바꾸고 시리얼 값을 관찰한다.",
      "0~1023 입력이 0~255 출력으로 변하는지 비교한다.",
      "map의 마지막 두 값을 255, 0으로 바꾸어 반대 동작을 확인한다.",
    ],
    code: [
      "const int LDR_PIN = A0;",
      "const int LED_PWM_PIN = 9;",
      "",
      "void setup() {",
      "  pinMode(LED_PWM_PIN, OUTPUT);",
      "  Serial.begin(9600);",
      "}",
      "",
      "void loop() {",
      "  int lightValue = analogRead(LDR_PIN);",
      "  int brightness = map(lightValue, 0, 1023, 0, 255);",
      "  brightness = constrain(brightness, 0, 255);",
      "",
      "  analogWrite(LED_PWM_PIN, brightness);",
      "  Serial.print(\"ADC=\");",
      "  Serial.print(lightValue);",
      "  Serial.print(\"  PWM=\");",
      "  Serial.println(brightness);",
      "  delay(100);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "analogRead(A0)", meaning: "A0 전압을 10비트 값 0~1023으로 변환해 읽습니다." },
      { code: "map(..., 0, 1023, 0, 255)", meaning: "1024단계 입력 범위를 256단계 PWM 범위로 비례 변환합니다." },
      { code: "constrain(..., 0, 255)", meaning: "계산된 출력값이 PWM 허용 범위를 벗어나지 않게 제한합니다." },
      { code: "analogWrite(D9, brightness)", meaning: "D9의 PWM 듀티비를 바꿔 LED의 평균 밝기를 조절합니다." },
      { code: "delay(100)", meaning: "센서값을 0.1초마다 갱신해 지나치게 빠른 출력을 줄입니다." },
    ],
    expected: "빛이 밝아져 A0 값이 커지면 LED가 밝아집니다. map의 출력 범위를 255→0으로 뒤집으면 어두울수록 밝아집니다.",
    challenge: "어두울수록 LED가 밝아지는 자동 조명으로 바꾸고, ADC가 300 미만일 때만 동작하도록 조건을 추가하세요.",
    errors: [
      { symptom: "값이 항상 0 또는 1023", cause: "A0가 전압 분배 중간점이 아니거나 회로가 끊김", fix: "LDR·10kΩ의 접점과 5V·GND를 확인" },
      { symptom: "밝기 조절 없이 켜짐/꺼짐만 보임", cause: "PWM이 아닌 핀 사용", fix: "~ 표시가 있는 D9에 LED 연결" },
    ],
    quiz: {
      question: "Arduino Uno의 analogRead와 analogWrite 값 범위를 바르게 짝지은 것은?",
      options: ["0~255 / 0~1023", "0~1023 / 0~255", "0~1024 / 0~256", "0~5 / 0~5"],
      answer: 1,
      explanation: "Uno의 ADC 입력은 10비트 값 0~1023, 기본 PWM 출력은 8비트 값 0~255를 사용합니다.",
    },
    examPrompts: [
      { type: "개념형", prompt: "PWM이 연속적인 아날로그 전압을 직접 출력하는 것이 아닌데도 LED 밝기가 달라 보이는 이유를 쓰시오." },
      { type: "범위 변환", prompt: "ADC 입력 0~1023을 PWM 255~0으로 반대로 변환하는 map() 문장을 작성하시오." },
      { type: "회로 해석", prompt: "LDR과 10kΩ 저항의 위치를 바꾸면 밝기에 따른 A0 값의 증가 방향이 달라지는 이유를 설명하시오." },
    ],
    teacher: "1024단계와 최댓값 1023, 256단계와 최댓값 255를 반드시 구분합니다. PWM은 빠른 디지털 펄스라는 점을 시간 비율로 설명합니다.",
  },
  {
    id: 5,
    shortTitle: "부저·모터",
    title: "부저와 서보모터로 소리와 움직임 출력하기",
    subtitle: "주파수는 음높이로, 각도 명령은 모터의 위치로 변환됩니다.",
    duration: "핵심 20분",
    input: "프로그램의 주파수·각도",
    output: "부저 소리·서보 회전",
    objectives: [
      "tone()의 주파수와 음높이 관계를 설명할 수 있다.",
      "Servo 객체와 write()로 목표 각도를 제어할 수 있다.",
      "모터 전원을 GPIO 핀에 직접 연결하면 안 되는 이유를 설명할 수 있다.",
    ],
    concepts: [
      { title: "주파수", body: "tone(핀, 주파수)는 1초 동안 반복되는 진동 횟수를 Hz로 정합니다. 값이 커질수록 높은 음이 납니다.", exam: "주파수와 음높이의 관계를 묻습니다." },
      { title: "서보모터", body: "일반적인 취미용 서보는 write(각도) 명령으로 0~180° 범위의 목표 위치를 제어합니다.", exam: "속도 제어가 아니라 위치 제어임을 구분합니다." },
      { title: "라이브러리와 객체", body: "Servo.h를 불러오고 Servo gate;로 객체를 만든 뒤 attach()로 신호 핀을 연결합니다.", exam: "attach와 write의 역할을 구분합니다." },
      { title: "전원과 공통 GND", body: "모터는 GPIO가 공급할 수 있는 전류보다 많이 필요할 수 있어 별도 전원을 사용하고 GND를 공통으로 연결합니다.", exam: "실물 회로의 전원 안전과 공통 접지를 묻습니다." },
    ],
    parts: ["Arduino Uno R3", "SG90 서보모터", "피에조 부저", "외부 5V 전원(실물 권장)", "점퍼선"],
    wiring: [
      { from: "서보 Signal", to: "D9", note: "각도 제어 신호" },
      { from: "서보 VCC / GND", to: "5V / GND", note: "실물에서는 별도 5V 전원 권장, GND 공통" },
      { from: "피에조 + / -", to: "D10 / GND", note: "음높이 출력" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "부저와 서보 공개 회로를 참고하고 D9 서보·D10 부저 기준으로 아래 코드를 실행합니다.",
    steps: [
      "서보의 Signal·VCC·GND 선을 구분해 연결한다.",
      "피에조 부저를 D10과 GND에 연결한다.",
      "실행 전 0°→90°→180° 순서를 예상한다.",
      "시뮬레이션을 실행해 각도와 음높이 변화를 관찰한다.",
      "마지막 각도를 45°로, 마지막 음을 523Hz로 바꾸어 결과를 설명한다.",
    ],
    code: [
      "#include <Servo.h>",
      "",
      "const int SERVO_PIN = 9;",
      "const int BUZZER_PIN = 10;",
      "Servo arm;",
      "",
      "void setup() {",
      "  arm.attach(SERVO_PIN);",
      "}",
      "",
      "void loop() {",
      "  arm.write(0);",
      "  tone(BUZZER_PIN, 262, 200);",
      "  delay(800);",
      "",
      "  arm.write(90);",
      "  tone(BUZZER_PIN, 330, 200);",
      "  delay(800);",
      "",
      "  arm.write(180);",
      "  tone(BUZZER_PIN, 392, 200);",
      "  delay(800);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "#include <Servo.h>", meaning: "서보 제어 기능이 들어 있는 라이브러리를 불러옵니다." },
      { code: "Servo arm;", meaning: "arm이라는 이름으로 서보 객체를 만듭니다." },
      { code: "arm.attach(9)", meaning: "서보 제어 신호를 D9와 연결합니다." },
      { code: "arm.write(90)", meaning: "서보의 목표 위치를 약 90°로 지정합니다." },
      { code: "tone(10, 330, 200)", meaning: "D10 부저에서 330Hz 음을 200ms 동안 냅니다." },
    ],
    expected: "서보가 0°·90°·180° 위치로 이동할 때 서로 다른 높이의 짧은 소리가 납니다.",
    challenge: "서보가 30°씩 이동할 때 주파수도 함께 높아지도록 for 반복문으로 바꾸세요.",
    errors: [
      { symptom: "서보가 떨리거나 Arduino가 재시작됨", cause: "모터의 순간 전류가 커 전압이 떨어짐", fix: "실물에서는 별도 5V 전원 사용 후 GND 공통 연결" },
      { symptom: "부저 음이 계속 남음", cause: "지속형 tone 뒤 noTone 누락", fix: "필요한 위치에서 noTone(BUZZER_PIN) 실행" },
    ],
    quiz: {
      question: "arm.write(90)의 의미로 가장 적절한 것은?",
      options: ["서보 속도를 90%로 설정", "서보 전압을 90V로 설정", "서보의 목표 위치를 약 90°로 설정", "90초 동안 서보를 실행"],
      answer: 2,
      explanation: "일반적인 위치 제어 서보에서 write()의 값은 목표 각도를 나타냅니다.",
    },
    examPrompts: [
      { type: "코드 해석", prompt: "세 tone()의 주파수가 커질수록 학생이 듣는 음높이가 어떻게 변하는지 쓰시오." },
      { type: "안전형", prompt: "DC모터나 서보모터의 전원을 GPIO 핀에 직접 연결하면 안 되는 이유를 전류와 관련지어 설명하시오." },
      { type: "라이브러리", prompt: "Servo arm;, arm.attach(9), arm.write(90)의 역할을 각각 설명하시오." },
    ],
    teacher: "모터는 출력 장치이지만 LED보다 필요한 전류가 큽니다. 시뮬레이션에서 되는 회로도 실물에서는 별도 전원과 공통 GND가 필요할 수 있음을 강조합니다.",
  },
  {
    id: 6,
    shortTitle: "종합 제어",
    title: "입력 센서로 빛·소리·움직임을 함께 제어하기",
    subtitle: "초음파와 조도 입력을 처리해 LED·부저·서보모터가 반응하는 자동 장치를 완성합니다.",
    duration: "종합 35분",
    input: "초음파 거리·LDR 조도",
    output: "PWM LED·부저·서보",
    objectives: [
      "두 센서 입력을 서로 다른 출력과 연결할 수 있다.",
      "정상 상태와 경고 상태의 출력 우선순위를 설명할 수 있다.",
      "전체 코드를 입력·처리·출력 부분으로 나누어 해석할 수 있다.",
    ],
    concepts: [
      { title: "입력", body: "초음파 센서는 거리의 디지털 타이밍을, LDR 회로는 밝기의 아날로그 전압을 제공합니다.", exam: "두 센서의 입력 방식 차이를 비교합니다." },
      { title: "처리", body: "조도값은 LED 밝기로 변환하고, 거리는 15cm 임계값과 비교해 경고 상태를 결정합니다.", exam: "map과 if가 각각 담당하는 처리 역할을 묻습니다." },
      { title: "출력 우선순위", body: "물체가 가까우면 자동 밝기보다 경고가 우선되어 LED 최대 밝기·부저·서보가 함께 작동합니다.", exam: "조건문 위치가 출력 우선순위에 미치는 영향을 분석합니다." },
      { title: "통합 테스트", body: "센서 하나씩 확인한 뒤 출력 하나씩 확인하고 마지막에 전체를 결합해야 오류 원인을 좁힐 수 있습니다.", exam: "전원→GND→핀→부품→코드 순서의 진단 문제로 연결합니다." },
    ],
    parts: ["Arduino Uno R3", "HC-SR04", "LDR", "10kΩ 저항", "LED·220Ω", "피에조 부저", "SG90 서보"],
    wiring: [
      { from: "HC-SR04 TRIG / ECHO", to: "D7 / D6", note: "거리 입력" },
      { from: "LDR 전압 분배 중간점", to: "A0", note: "조도 입력" },
      { from: "LED 애노드", to: "D3(~)를 거쳐 220Ω", note: "PWM 밝기·경고 출력" },
      { from: "피에조 +", to: "D10", note: "경고음" },
      { from: "서보 Signal", to: "D9", note: "경고 장치 또는 문 열기" },
    ],
    simulatorUrl: "https://www.tinkercad.com/classrooms/dky0pTDB1Aj/activities",
    simulatorNote: "초음파·서보·LED·부저 통합 공개 회로를 참고합니다. LDR를 추가하고 아래 핀 배치와 전체 코드를 기준으로 완성합니다.",
    steps: [
      "먼저 LDR→PWM LED만 연결해 밝기 자동 조절을 확인한다.",
      "초음파 센서를 추가하고 시리얼 모니터에서 거리만 확인한다.",
      "서보와 부저를 추가한 뒤 전원·GND·핀을 다시 점검한다.",
      "거리 15cm 이상에서 빛을 바꾸며 자동 밝기를 확인한다.",
      "거리 15cm 미만으로 바꾸어 경고 빛·소리·서보가 동시에 작동하는지 확인한다.",
      "임계값 또는 PWM 방향 중 하나를 수정하고 변경 결과를 설명한다.",
    ],
    code: [
      "#include <Servo.h>",
      "",
      "const int TRIG_PIN = 7;",
      "const int ECHO_PIN = 6;",
      "const int LDR_PIN = A0;",
      "const int LED_PWM_PIN = 3;",
      "const int SERVO_PIN = 9;",
      "const int BUZZER_PIN = 10;",
      "Servo gate;",
      "",
      "void setup() {",
      "  pinMode(TRIG_PIN, OUTPUT);",
      "  pinMode(ECHO_PIN, INPUT);",
      "  pinMode(LED_PWM_PIN, OUTPUT);",
      "  gate.attach(SERVO_PIN);",
      "  gate.write(0);",
      "  Serial.begin(9600);",
      "}",
      "",
      "float readDistanceCm() {",
      "  digitalWrite(TRIG_PIN, LOW);",
      "  delayMicroseconds(2);",
      "  digitalWrite(TRIG_PIN, HIGH);",
      "  delayMicroseconds(10);",
      "  digitalWrite(TRIG_PIN, LOW);",
      "  unsigned long duration = pulseIn(ECHO_PIN, HIGH, 30000UL);",
      "  if (duration == 0) return -1.0;",
      "  return duration * 0.0343 / 2.0;",
      "}",
      "",
      "void loop() {",
      "  int lightValue = analogRead(LDR_PIN);",
      "  int autoBrightness = map(lightValue, 0, 1023, 30, 220);",
      "  float distanceCm = readDistanceCm();",
      "",
      "  if (distanceCm > 0 && distanceCm < 15.0) {",
      "    analogWrite(LED_PWM_PIN, 255);",
      "    tone(BUZZER_PIN, 1000);",
      "    gate.write(90);",
      "  } else {",
      "    analogWrite(LED_PWM_PIN, autoBrightness);",
      "    noTone(BUZZER_PIN);",
      "    gate.write(0);",
      "  }",
      "",
      "  Serial.print(\"light=\");",
      "  Serial.print(lightValue);",
      "  Serial.print(\" distance=\");",
      "  Serial.println(distanceCm);",
      "  delay(200);",
      "}",
    ].join("\n"),
    lineNotes: [
      { code: "float readDistanceCm()", meaning: "초음파 측정 과정을 함수로 묶어 loop()를 읽기 쉽게 만듭니다." },
      { code: "if (duration == 0) return -1.0;", meaning: "시간 초과를 정상 거리 0cm와 구분하기 위해 -1을 반환합니다." },
      { code: "map(..., 30, 220)", meaning: "조도값을 완전 꺼짐이 아닌 30~220 범위의 LED 밝기로 변환합니다." },
      { code: "distanceCm > 0 && distanceCm < 15.0", meaning: "정상 측정값이면서 15cm보다 가까울 때만 경고 상태로 들어갑니다." },
      { code: "analogWrite(..., 255); tone(...); gate.write(90);", meaning: "경고 상태에서 빛·소리·움직임 세 출력을 함께 실행합니다." },
    ],
    expected: "평소에는 조도값에 따라 LED 밝기가 변합니다. 물체가 15cm 안으로 오면 LED가 최대 밝기로 켜지고 부저가 울리며 서보가 90°로 이동합니다.",
    challenge: "거리 15cm 미만이면서 주변도 어두울 때만 경고하도록 && 조건을 추가하고, 어떤 경우에 경고가 울리는지 진리표로 나타내세요.",
    errors: [
      { symptom: "각 부품은 따로 되지만 함께 연결하면 불안정", cause: "모터 전류·GND·전원 부족", fix: "출력 하나씩 다시 시험하고 실물 모터는 외부 전원+공통 GND 사용" },
      { symptom: "센서 오류 때도 경고가 울림", cause: "-1 오류값을 가까운 거리로 판정", fix: "distanceCm > 0 조건을 먼저 검사" },
    ],
    quiz: {
      question: "종합 코드에서 distanceCm > 0 조건을 함께 검사하는 이유는?",
      options: ["LED를 더 밝게 하기 위해", "서보 각도를 0도로 만들기 위해", "시간 초과를 나타내는 -1을 가까운 거리로 잘못 판정하지 않기 위해", "조도값을 1023으로 만들기 위해"],
      answer: 2,
      explanation: "readDistanceCm()은 측정 실패 시 -1을 반환합니다. 양수 조건이 없으면 -1도 15보다 작아 경고가 잘못 켜질 수 있습니다.",
    },
    examPrompts: [
      { type: "구조 분석", prompt: "종합 코드에서 입력·처리·출력에 해당하는 문장을 각각 두 개 이상 찾아 쓰시오." },
      { type: "오류 진단", prompt: "초음파 센서값은 정상인데 서보 연결 후 Arduino가 재시작되는 원인과 해결 방법을 쓰시오." },
      { type: "설계형", prompt: "거리와 조도를 이용해 경고 조건을 새롭게 정하고 필요한 조건식을 작성하시오." },
    ],
    teacher: "처음부터 전체 회로를 조립하지 말고 LDR·초음파·출력 순서로 기능을 분리해 확인하게 합니다. 이것이 수행평가의 오류 진단 과정이 됩니다.",
  },
];

export const arduinoPicoComparison = [
  { item: "대표 보드", arduino: "Arduino Uno R3 · ATmega328P", pico: "Raspberry Pi Pico · RP2040", meaning: "둘 다 센서 입력을 처리해 출력을 제어하는 마이크로컨트롤러 보드" },
  { item: "기본 논리 전압", arduino: "5V", pico: "3.3V", meaning: "Pico GPIO에 5V 신호를 직접 넣으면 안 됨" },
  { item: "주 언어", arduino: "Arduino C/C++ 스케치", pico: "MicroPython", meaning: "문법은 달라도 입력→처리→출력 구조는 같음" },
  { item: "개발·실습 도구", arduino: "Tinkercad·Arduino IDE", pico: "Wokwi·Thonny", meaning: "가상 확인 후 실제 장치 실행" },
  { item: "디지털 출력", arduino: "pinMode(), digitalWrite()", pico: "Pin(..., Pin.OUT), value()", meaning: "핀을 출력으로 정한 뒤 HIGH/LOW 상태 제어" },
  { item: "아날로그 입력", arduino: "10비트 ADC · 0~1023", pico: "하드웨어 12비트 ADC · read_u16()은 0~65535로 변환", meaning: "연속 전압을 정해진 단계의 숫자로 바꿈" },
  { item: "PWM 출력", arduino: "analogWrite() · 0~255", pico: "PWM.duty_u16() · 0~65535", meaning: "빠른 펄스의 켜짐 비율로 평균 출력을 조절" },
  { item: "코드 저장", arduino: "스케치를 컴파일해 업로드", pico: "MicroPython 코드를 main.py로 저장", meaning: "전원을 다시 연결했을 때 자동 실행하는 방식이 다름" },
];
