import {
  Cpu,
  FlaskConical,
  GraduationCap,
  Lightbulb,
  Sparkles,
  ThermometerSun,
  Volume2,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

export type Lesson = {
  id: number;
  phase: string;
  title: string;
  subtitle: string;
  duration: string;
  icon: LucideIcon;
  objectives: string[];
  concepts: { title: string; body: string }[];
  parts: string[];
  wiring: { from: string; to: string; note: string }[];
  steps: string[];
  code: string;
  expected: string;
  challenge: string;
  errors: { symptom: string; cause: string; fix: string }[];
  quiz: { question: string; options: string[]; answer: number; explanation: string };
  teacher: string;
  exam: string;
};

export const lessons: Lesson[] = [
  {
    id: 1,
    phase: "AI 맛보기",
    title: "피지컬 컴퓨팅 첫걸음",
    subtitle: "입력·처리·출력으로 현실의 문제를 해결해요",
    duration: "50분",
    icon: Sparkles,
    objectives: [
      "피지컬 컴퓨팅의 의미를 설명할 수 있다.",
      "센서·처리 장치·액추에이터의 역할을 구분할 수 있다.",
      "AI 시스템과 피지컬 컴퓨팅의 공통 흐름을 찾을 수 있다.",
    ],
    concepts: [
      { title: "입력", body: "센서가 온도·빛·소리처럼 현실의 변화를 전기 신호로 바꿉니다." },
      { title: "처리", body: "프로그램이 입력값을 비교하고, 어떤 출력을 만들지 결정합니다." },
      { title: "출력", body: "LED·부저 같은 액추에이터가 전기 신호를 빛이나 소리로 바꿉니다." },
      { title: "AI와의 연결", body: "조건문은 정해진 규칙으로, AI는 데이터에서 학습한 기준으로 판단할 수 있습니다." },
    ],
    parts: ["Raspberry Pi Pico H", "Micro-USB 데이터 케이블", "PC", "VS Code"],
    wiring: [
      { from: "Pico", to: "PC USB 포트", note: "데이터 전송이 가능한 케이블 사용" },
      { from: "내장 LED", to: "GP25", note: "외부 배선 없이 첫 출력 확인" },
    ],
    steps: [
      "Pico의 USB 단자, GPIO 핀, GND 핀을 찾아본다.",
      "주변 스마트 장치 하나를 골라 입력·처리·출력을 구분한다.",
      "코드를 Pico의 main.py로 저장하고 내장 LED를 관찰한다.",
      "LED가 켜지는 과정의 입력·처리·출력을 말해 본다.",
    ],
    code: [
      "from machine import Pin",
      "",
      "led = Pin(25, Pin.OUT)",
      "led.value(1)",
      "print('Pico의 첫 출력: LED ON')",
    ].join("\n"),
    expected: "내장 LED가 켜지고 터미널에 ‘Pico의 첫 출력: LED ON’이 표시됩니다.",
    challenge: "스마트 가습기를 예로 들어 입력·처리·출력 요소를 각각 한 가지씩 적어 보세요.",
    errors: [
      { symptom: "Pico가 PC에 보이지 않음", cause: "충전 전용 케이블 사용", fix: "데이터 전송 지원 케이블로 교체" },
      { symptom: "LED가 켜지지 않음", cause: "코드를 PC에만 저장함", fix: "Pico 장치에 main.py로 저장" },
    ],
    quiz: {
      question: "다음 중 액추에이터에 해당하는 것은?",
      options: ["온도 센서", "빛 센서", "LED", "심박 센서"],
      answer: 2,
      explanation: "LED는 전기 신호를 사람이 볼 수 있는 빛으로 바꾸는 출력 장치입니다.",
    },
    teacher: "AI를 어렵게 정의하기보다 ‘센서값을 받아 판단하고 행동한다’는 공통 구조를 먼저 체감하게 합니다. 장치 이름보다 입력·처리·출력 구분의 타당성을 확인합니다.",
    exam: "센서와 액추에이터의 차이를 ‘신호가 변환되는 방향’을 포함하여 서술하게 할 수 있습니다.",
  },
  {
    id: 2,
    phase: "기초 제어",
    title: "MicroPython과 내장 LED",
    subtitle: "반복되는 깜빡임을 코드로 만들어요",
    duration: "50분",
    icon: Cpu,
    objectives: [
      "MicroPython 프로그램의 실행 순서를 설명할 수 있다.",
      "Pin 객체를 출력 모드로 설정할 수 있다.",
      "sleep()으로 LED의 켜짐 시간을 제어할 수 있다.",
    ],
    concepts: [
      { title: "Pin", body: "Pico의 핀을 프로그램에서 다루기 위한 객체입니다. GP25는 내장 LED와 연결됩니다." },
      { title: "OUT", body: "핀이 외부로 전기 신호를 내보내도록 출력 모드로 정합니다." },
      { title: "while True", body: "들여쓴 명령을 끝없이 반복하여 장치가 계속 동작하게 합니다." },
      { title: "sleep", body: "프로그램을 지정한 초만큼 잠시 멈춰 사람이 변화를 볼 수 있게 합니다." },
    ],
    parts: ["Pico H", "Micro-USB 데이터 케이블", "VS Code + MicroPico 확장"],
    wiring: [{ from: "내장 LED", to: "GP25", note: "외부 배선 없음" }],
    steps: [
      "VS Code에서 Pico 장치 연결을 확인한다.",
      "예제 코드를 main.py에 입력해 Pico에 저장한다.",
      "LED가 0.5초 간격으로 켜지고 꺼지는지 관찰한다.",
      "sleep 값을 0.1, 1, 2로 바꾸어 차이를 기록한다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "",
      "led = Pin(25, Pin.OUT)",
      "",
      "while True:",
      "    led.on()",
      "    sleep(0.5)",
      "    led.off()",
      "    sleep(0.5)",
    ].join("\n"),
    expected: "내장 LED가 0.5초 켜지고 0.5초 꺼지는 동작을 계속 반복합니다.",
    challenge: "LED가 짧게 두 번 깜빡인 뒤 1초 쉬는 구조로 코드를 바꾸세요.",
    errors: [
      { symptom: "IndentationError", cause: "while 아래 들여쓰기 불일치", fix: "반복할 네 줄 앞에 같은 4칸 들여쓰기" },
      { symptom: "NameError: sleep", cause: "sleep을 가져오지 않음", fix: "from time import sleep 추가" },
    ],
    quiz: {
      question: "sleep(0.5)의 의미로 옳은 것은?",
      options: ["0.5분 정지", "0.5초 정지", "LED 밝기 50%", "0.5회 반복"],
      answer: 1,
      explanation: "MicroPython의 sleep() 괄호 안 숫자는 초 단위의 대기 시간입니다.",
    },
    teacher: "코드를 먼저 설명하기보다 LED의 예상 움직임을 손가락으로 표현하게 한 뒤 실행합니다. 반복과 순차 구조가 하드웨어 움직임으로 바뀌는 순간을 강조합니다.",
    exam: "while True와 들여쓰기가 LED 반복 동작에 미치는 영향을 묻는 코드 추적 문제로 연결합니다.",
  },
  {
    id: 3,
    phase: "기초 제어",
    title: "변수와 반복 패턴",
    subtitle: "같은 코드도 값에 따라 다르게 움직여요",
    duration: "50분",
    icon: Zap,
    objectives: [
      "변수로 시간과 반복 횟수를 제어할 수 있다.",
      "for와 range의 동작을 실제 출력으로 확인할 수 있다.",
      "코드의 일부만 수정해 새로운 패턴을 만들 수 있다.",
    ],
    concepts: [
      { title: "변수", body: "값에 이름을 붙여 저장합니다. 값을 한 번 바꾸면 관련 동작이 함께 바뀝니다." },
      { title: "for", body: "정해진 횟수만큼 명령을 반복할 때 사용합니다." },
      { title: "range(3)", body: "0, 1, 2의 세 값을 차례로 만들어 반복을 세 번 실행합니다." },
      { title: "패턴", body: "켜짐·꺼짐 시간과 횟수의 규칙을 조합한 출력 순서입니다." },
    ],
    parts: ["Pico H", "Micro-USB 데이터 케이블", "VS Code"],
    wiring: [{ from: "내장 LED", to: "GP25", note: "외부 배선 없음" }],
    steps: [
      "blink_time과 count가 어느 명령에 사용되는지 표시한다.",
      "세 번 깜빡인 뒤 꺼진 상태로 끝나는지 확인한다.",
      "count를 5로 바꾸고 실제 반복 횟수를 센다.",
      "자신만의 긴 신호·짧은 신호 패턴을 설계한다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "",
      "led = Pin(25, Pin.OUT)",
      "blink_time = 0.2",
      "count = 3",
      "",
      "for i in range(count):",
      "    led.on()",
      "    sleep(blink_time)",
      "    led.off()",
      "    sleep(blink_time)",
      "    print(i + 1, '번째 신호')",
    ].join("\n"),
    expected: "LED가 0.2초 간격으로 세 번 깜빡이고 반복 번호가 1부터 3까지 출력됩니다.",
    challenge: "blink_time은 그대로 두고 총 동작 시간을 두 배로 만드는 가장 간단한 수정 방법을 찾으세요.",
    errors: [
      { symptom: "두 번만 실행된 것처럼 보임", cause: "range(3)의 값을 횟수와 혼동", fix: "값은 0·1·2지만 반복은 세 번임을 출력으로 확인" },
      { symptom: "LED가 계속 켜져 있음", cause: "led.off()가 for 바깥에 있음", fix: "켜기·끄기 명령을 모두 반복문 안에 배치" },
    ],
    quiz: {
      question: "for i in range(4): 아래 명령은 몇 번 반복되는가?",
      options: ["3번", "4번", "5번", "무한 반복"],
      answer: 1,
      explanation: "range(4)는 0부터 3까지 네 개의 값을 만들므로 네 번 반복합니다.",
    },
    teacher: "변수명을 speed보다 blink_time처럼 역할이 드러나게 합니다. 수정한 값과 관찰 결과를 짝지어 기록하게 합니다.",
    exam: "range의 생성값과 반복 횟수를 구분하고 출력 결과를 순서대로 쓰게 합니다.",
  },
  {
    id: 4,
    phase: "빛 출력",
    title: "NeoPixel 스틱 첫 4개 제어",
    subtitle: "한 가닥의 데이터 선으로 여러 LED를 다뤄요",
    duration: "50분",
    icon: Lightbulb,
    objectives: [
      "NeoPixel의 전원·GND·데이터 핀을 구분할 수 있다.",
      "RGB 값으로 빛의 색을 표현할 수 있다.",
      "인덱스를 이용해 원하는 LED를 선택할 수 있다.",
    ],
    concepts: [
      { title: "RGB", body: "빨강·초록·파랑의 밝기를 0~255로 조합해 색을 만듭니다." },
      { title: "인덱스", body: "LED 번호는 0부터 시작합니다. 기본 실습은 8개 스틱의 0~3번을 사용합니다." },
      { title: "write()", body: "메모리에 정한 색을 실제 NeoPixel에 한꺼번에 반영합니다." },
      { title: "공통 GND", body: "Pico와 부품이 같은 0V 기준을 공유해야 데이터가 정확히 전달됩니다." },
    ],
    parts: ["Pico H", "WS2812B 8-LED 스틱", "M-F 점퍼선 3개", "브레드보드"],
    wiring: [
      { from: "NeoPixel DIN", to: "GP0", note: "데이터 입력 방향 화살표 확인" },
      { from: "NeoPixel GND", to: "Pico GND", note: "반드시 공통 접지" },
      { from: "NeoPixel 5V", to: "Pico VBUS", note: "USB 전원, 배선 변경 전 USB 분리" },
    ],
    steps: [
      "USB를 분리한 상태에서 DIN·GND·5V를 연결한다.",
      "짝과 배선을 확인한 뒤 USB를 연결한다.",
      "0번 LED가 빨간색으로 켜지는지 확인한다.",
      "인덱스와 RGB 값을 바꾸어 다른 위치와 색을 시험한다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "",
      "pixels = NeoPixel(Pin(0), 4)",
      "pixels.fill((0, 0, 0))",
      "pixels[0] = (40, 0, 0)",
      "pixels.write()",
    ].join("\n"),
    expected: "8개 스틱의 첫 4개 중 첫 번째 NeoPixel이 낮은 밝기의 빨간색으로 켜집니다.",
    challenge: "기본 코드가 사용하는 네 번째 LED를 파란색으로 켜려면 인덱스와 RGB 값을 어떻게 바꿔야 할까요?",
    errors: [
      { symptom: "모든 LED가 꺼져 있음", cause: "write() 누락 또는 DIN 방향 반대", fix: "write()와 NeoPixel 입력 화살표 점검" },
      { symptom: "색이 불안정함", cause: "GND 미연결", fix: "NeoPixel GND와 Pico GND를 연결" },
    ],
    quiz: {
      question: "기본 코드에서 사용하는 4개 NeoPixel의 마지막 인덱스는?",
      options: ["3", "4", "7", "255"],
      answer: 0,
      explanation: "인덱스는 0부터 시작하므로 기본 코드의 네 위치는 0~3입니다.",
    },
    teacher: "처음부터 최대 밝기 255를 쓰지 않고 20~40 정도로 확인합니다. VBUS는 NeoPixel 전원에만 사용하며 센서는 3.3V에 연결하도록 구분합니다.",
    exam: "pixels[3] = (0, 30, 0)이 선택하는 LED 위치와 색을 함께 묻습니다.",
  },
  {
    id: 5,
    phase: "미디어 아트",
    title: "16-LED 링 미디어 아트",
    subtitle: "반복문과 색 목록으로 작품을 만들어요",
    duration: "50분",
    icon: Waves,
    objectives: [
      "리스트에 여러 RGB 값을 저장할 수 있다.",
      "중첩된 반복 흐름을 따라갈 수 있다.",
      "의도한 분위기에 맞는 빛 패턴을 설계할 수 있다.",
    ],
    concepts: [
      { title: "색 목록", body: "여러 RGB 튜플을 리스트에 저장하면 색을 순서대로 꺼내 쓸 수 있습니다." },
      { title: "중첩 반복", body: "색을 고르는 반복 안에서 LED 위치를 고르는 반복이 실행됩니다." },
      { title: "잔상", body: "이전 LED를 끄고 다음 LED를 켜면 빛이 이동하는 것처럼 보입니다." },
      { title: "미디어 아트", body: "코드·빛·시간의 규칙을 이용해 생각이나 분위기를 표현합니다." },
    ],
    parts: ["Pico H", "WS2812B 16-LED 링(SZH-LD083)", "점퍼선", "브레드보드"],
    wiring: [
      { from: "NeoPixel DIN", to: "GP0", note: "링의 데이터 IN 핀" },
      { from: "NeoPixel GND", to: "Pico GND", note: "공통 접지" },
      { from: "NeoPixel 5V", to: "Pico VBUS", note: "USB 전원" },
    ],
    steps: [
      "colors 리스트의 세 가지 색을 예상한다.",
      "색과 위치가 바뀌는 순서를 관찰한다.",
      "sleep 값을 바꾸어 속도와 느낌을 비교한다.",
      "색 3개와 움직임 규칙으로 10초짜리 작품을 만든다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "",
      "pixels = NeoPixel(Pin(0), 16)",
      "colors = [(30, 0, 8), (20, 8, 0), (0, 12, 30)]",
      "",
      "while True:",
      "    for color in colors:",
      "        for i in range(16):",
      "            pixels.fill((0, 0, 0))",
      "            pixels[i] = color",
      "            pixels.write()",
      "            sleep(0.1)",
    ].join("\n"),
    expected: "분홍·주황·파랑 계열의 빛 한 점이 16-LED 링을 따라 차례로 이동합니다.",
    challenge: "빛이 왼쪽에서 오른쪽으로 이동한 뒤 다시 되돌아오도록 range를 추가하세요.",
    errors: [
      { symptom: "빛이 누적되어 모두 켜짐", cause: "pixels.fill((0, 0, 0)) 누락", fix: "새 위치를 켜기 전에 전체를 끔" },
      { symptom: "색이 너무 밝음", cause: "RGB 값을 255에 가깝게 설정", fix: "각 값을 40 이하로 시작" },
    ],
    quiz: {
      question: "움직이는 빛이 이전 위치에 남지 않게 하는 명령은?",
      options: ["pixels.write()", "sleep(0.1)", "pixels.fill((0, 0, 0))", "Pin(0)"],
      answer: 2,
      explanation: "fill((0, 0, 0))은 모든 LED를 꺼진 상태로 바꿉니다.",
    },
    teacher: "작품의 화려함보다 색·속도·이동 규칙에 의도가 드러나는지 질문합니다. 반복 실행 횟수는 표로 추적하게 합니다.",
    exam: "바깥 반복과 안쪽 반복의 실행 횟수를 곱하여 전체 write() 횟수를 계산하게 합니다.",
  },
  {
    id: 6,
    phase: "센서 입력",
    title: "DHT11 온습도 측정",
    subtitle: "교실의 환경을 숫자로 읽어요",
    duration: "50분",
    icon: ThermometerSun,
    objectives: [
      "DHT11이 측정하는 물리량을 설명할 수 있다.",
      "센서값을 변수에 저장하고 출력할 수 있다.",
      "측정 주기와 센서 오차의 의미를 이해할 수 있다.",
    ],
    concepts: [
      { title: "센서", body: "현실의 온도와 습도를 프로그램이 처리할 수 있는 값으로 바꿉니다." },
      { title: "측정 주기", body: "DHT11은 너무 자주 읽으면 오류가 날 수 있어 약 2초 간격을 둡니다." },
      { title: "변수", body: "temperature와 humidity에 측정 순간의 값을 저장합니다." },
      { title: "데이터", body: "한 번의 값보다 같은 조건에서 여러 번 측정한 값의 흐름이 더 유용합니다." },
    ],
    parts: ["Pico H", "DHT11 모듈", "M-F 점퍼선 3개", "브레드보드"],
    wiring: [
      { from: "DHT11 VCC", to: "Pico 3V3(OUT)", note: "센서는 3.3V 사용" },
      { from: "DHT11 DATA", to: "GP22", note: "데이터 핀" },
      { from: "DHT11 GND", to: "Pico GND", note: "공통 접지" },
    ],
    steps: [
      "USB를 분리하고 VCC·DATA·GND를 배선한다.",
      "짝과 전원 핀을 확인한 뒤 USB를 연결한다.",
      "온도와 습도가 2초마다 출력되는지 확인한다.",
      "센서를 손으로 감싸기 전과 후의 값을 비교한다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT11(Pin(22))",
      "",
      "while True:",
      "    sensor.measure()",
      "    temperature = sensor.temperature()",
      "    humidity = sensor.humidity()",
      "    print('온도:', temperature, '°C')",
      "    print('습도:', humidity, '%')",
      "    sleep(2)",
    ].join("\n"),
    expected: "터미널에 현재 온도(°C)와 상대 습도(%)가 약 2초마다 표시됩니다.",
    challenge: "온도가 27°C 이상이면 ‘더워요’, 아니면 ‘쾌적해요’를 출력하는 조건문을 추가하세요.",
    errors: [
      { symptom: "OSError가 가끔 발생", cause: "너무 짧은 측정 간격 또는 읽기 실패", fix: "sleep(2)를 유지하고 다시 측정" },
      { symptom: "값이 전혀 나오지 않음", cause: "VCC와 GND를 반대로 연결", fix: "즉시 USB를 분리하고 핀 표기 재확인" },
    ],
    quiz: {
      question: "DHT11 센서 VCC에 연결할 Pico 핀은?",
      options: ["VBUS", "3V3(OUT)", "GP28", "RUN"],
      answer: 1,
      explanation: "DHT11 센서 모듈은 Pico의 3.3V 출력과 GND를 기준으로 연결합니다.",
    },
    teacher: "센서값을 절대적으로 정확하다고 단정하지 않게 합니다. 같은 위치·같은 시간이라는 조건을 맞추고 변화의 경향을 해석하게 합니다.",
    exam: "sensor.measure() 이후 temperature()를 호출하는 순서와 sleep(2)의 필요성을 묻습니다.",
  },
  {
    id: 7,
    phase: "자동 제어",
    title: "온도에 반응하는 NeoPixel",
    subtitle: "센서 입력을 조건문으로 판단해 빛을 바꿔요",
    duration: "50분",
    icon: FlaskConical,
    objectives: [
      "입력값을 조건문으로 분류할 수 있다.",
      "DHT11과 NeoPixel을 하나의 프로그램에서 제어할 수 있다.",
      "임계값이 자동 제어 결과에 미치는 영향을 설명할 수 있다.",
    ],
    concepts: [
      { title: "임계값", body: "상태를 나누는 기준값입니다. 여기서는 27°C를 기준으로 색을 바꿉니다." },
      { title: "조건문", body: "조건이 참일 때와 거짓일 때 서로 다른 출력을 선택합니다." },
      { title: "자동 제어", body: "사람이 매번 누르지 않아도 입력값에 따라 장치가 스스로 반응합니다." },
      { title: "전체 흐름", body: "DHT11 입력 → 온도 비교 처리 → NeoPixel 색 출력 순서입니다." },
    ],
    parts: ["Pico H", "DHT11", "WS2812B 8-LED 스틱", "점퍼선", "브레드보드"],
    wiring: [
      { from: "DHT11 DATA", to: "GP22", note: "VCC는 3V3, GND는 공통" },
      { from: "NeoPixel DIN", to: "GP0", note: "5V는 VBUS, GND는 공통" },
      { from: "두 부품 GND", to: "Pico GND", note: "모든 장치의 기준 전압 공유" },
    ],
    steps: [
      "두 부품의 전원 전압 차이를 확인하고 배선한다.",
      "현재 온도가 어느 색으로 표시될지 예상한다.",
      "센서를 손으로 감싸 온도 변화를 만든다.",
      "임계값을 교실 상황에 맞게 수정하고 이유를 기록한다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT11(Pin(22))",
      "pixels = NeoPixel(Pin(0), 4)",
      "",
      "while True:",
      "    sensor.measure()",
      "    temp = sensor.temperature()",
      "    if temp >= 27:",
      "        color = (35, 0, 0)",
      "    else:",
      "        color = (0, 12, 30)",
      "    pixels.fill(color)",
      "    pixels.write()",
      "    print(temp, '°C')",
      "    sleep(2)",
    ].join("\n"),
    expected: "온도가 27°C 이상이면 빨간색, 낮으면 파란색으로 스틱의 첫 4개 LED가 켜집니다.",
    challenge: "24°C 미만은 파랑, 24~27°C는 초록, 27°C 이상은 빨강이 되도록 elif를 사용하세요.",
    errors: [
      { symptom: "온도는 나오지만 LED가 꺼짐", cause: "write() 누락 또는 전원 오류", fix: "write()와 VBUS·GND·DIN 확인" },
      { symptom: "색이 기준 근처에서 자주 바뀜", cause: "값이 임계값 주변에서 흔들림", fix: "켜짐·꺼짐 기준을 다르게 두는 방법 토의" },
    ],
    quiz: {
      question: "temp가 28일 때 선택되는 색은?",
      options: ["(0, 12, 30)", "(35, 0, 0)", "(0, 0, 0)", "오류가 난다"],
      answer: 1,
      explanation: "28은 27 이상이므로 if 조건이 참이 되어 빨간색이 선택됩니다.",
    },
    teacher: "27°C가 정답이 아니라 목적과 환경에 따라 정하는 기준임을 강조합니다. 경계값 26·27·28의 결과를 표로 만들게 합니다.",
    exam: "조건식의 경계값에서 어떤 분기가 실행되는지 판단하고 입력·처리·출력을 구분하게 합니다.",
  },
  {
    id: 8,
    phase: "아날로그 입력",
    title: "심박 센서와 ADC",
    subtitle: "연속적인 전압을 숫자로 바꾸어 관찰해요",
    duration: "50분",
    icon: Waves,
    objectives: [
      "아날로그 신호와 디지털 값의 차이를 설명할 수 있다.",
      "ADC로 GP28의 센서값을 읽을 수 있다.",
      "여러 측정값의 변화와 노이즈를 구분해 관찰할 수 있다.",
    ],
    concepts: [
      { title: "아날로그", body: "시간에 따라 연속적으로 변하는 전압 신호입니다." },
      { title: "ADC", body: "아날로그 전압을 프로그램이 처리할 수 있는 디지털 숫자로 바꿉니다." },
      { title: "read_u16", body: "MicroPython에서는 ADC 결과를 0~65535 범위로 읽어 줍니다." },
      { title: "노이즈", body: "움직임·접촉 상태·주변 전기 신호 때문에 값이 순간적으로 흔들릴 수 있습니다." },
    ],
    parts: ["Pico H", "아날로그 Pulse Sensor", "M-F 점퍼선 3개", "브레드보드"],
    wiring: [
      { from: "Pulse Sensor +", to: "Pico 3V3(OUT)", note: "전원" },
      { from: "Pulse Sensor S", to: "GP28 / ADC2", note: "아날로그 신호 입력" },
      { from: "Pulse Sensor -", to: "Pico GND", note: "공통 접지" },
    ],
    steps: [
      "USB를 분리하고 센서의 +·S·-를 확인해 배선한다.",
      "센서에 가볍게 접촉한 뒤 움직이지 않고 관찰한다.",
      "연속된 20개 값 중 최댓값과 최솟값을 기록한다.",
      "접촉을 느슨하게 했을 때 노이즈 변화를 비교한다.",
    ],
    code: [
      "from machine import ADC, Pin",
      "from time import sleep",
      "",
      "pulse = ADC(Pin(28))",
      "",
      "while True:",
      "    value = pulse.read_u16()",
      "    bars = value // 4000",
      "    print(value, '|' + '■' * bars)",
      "    sleep(0.05)",
    ].join("\n"),
    expected: "0~65535 범위의 값과 간단한 막대가 빠르게 변하며 터미널에 표시됩니다.",
    challenge: "최근 5개의 값을 리스트에 모아 평균을 출력하면 순간적인 흔들림이 어떻게 달라지는지 확인하세요.",
    errors: [
      { symptom: "값이 0 또는 최대값에 고정", cause: "신호선이 GP28에 연결되지 않음", fix: "S 신호선과 ADC2 핀 재확인" },
      { symptom: "값이 매우 불규칙함", cause: "접촉·움직임·GND 불안정", fix: "움직임을 줄이고 GND 연결 확인" },
    ],
    quiz: {
      question: "ADC의 역할로 가장 알맞은 것은?",
      options: ["빛을 소리로 바꿈", "아날로그 전압을 디지털 값으로 바꿈", "전압을 5V로 높임", "파일을 저장함"],
      answer: 1,
      explanation: "ADC는 연속적인 전압을 프로그램이 계산할 수 있는 숫자로 변환합니다.",
    },
    teacher: "이 활동은 신호와 ADC 원리를 관찰하는 교육용 실습이며 의료 측정이나 진단이 아님을 분명히 합니다. 개인 수치 비교보다 파형 변화와 노이즈 원인에 집중합니다.",
    exam: "Pico ADC의 하드웨어 분해능과 read_u16 반환 범위를 구분하는 심화 문항으로 확장합니다.",
  },
  {
    id: 9,
    phase: "소리 출력",
    title: "PWM 부저 알림",
    subtitle: "주파수와 듀티비로 소리를 만들어요",
    duration: "50분",
    icon: Volume2,
    objectives: [
      "PWM 신호의 주파수와 듀티비를 설명할 수 있다.",
      "수동 부저로 서로 다른 높이의 소리를 만들 수 있다.",
      "센서 조건에 맞는 알림 패턴을 설계할 수 있다.",
    ],
    concepts: [
      { title: "PWM", body: "디지털 신호를 매우 빠르게 켰다 껐다 하여 출력의 세기를 조절합니다." },
      { title: "주파수", body: "1초에 신호가 반복되는 횟수이며, 값이 클수록 높은 소리가 납니다." },
      { title: "듀티비", body: "한 주기에서 켜져 있는 비율입니다. duty_u16(0)은 소리를 끕니다." },
      { title: "수동 부저", body: "PWM 주파수에 따라 음높이가 달라지는 부저입니다." },
    ],
    parts: ["Pico H", "수동 부저", "M-M 점퍼선", "브레드보드"],
    wiring: [
      { from: "부저 +", to: "GP16", note: "PWM 출력 핀" },
      { from: "부저 -", to: "Pico GND", note: "극성 표기 확인" },
    ],
    steps: [
      "USB를 분리하고 부저의 +와 -를 확인해 연결한다.",
      "262Hz, 330Hz, 392Hz의 높이를 비교한다.",
      "duty_u16(12000)과 duty_u16(0)의 역할을 확인한다.",
      "두 음을 조합해 짧고 분명한 알림음을 만든다.",
    ],
    code: [
      "from machine import Pin, PWM",
      "from time import sleep",
      "",
      "buzzer = PWM(Pin(16))",
      "notes = [262, 330, 392]",
      "",
      "for note in notes:",
      "    buzzer.freq(note)",
      "    buzzer.duty_u16(12000)",
      "    sleep(0.25)",
      "    buzzer.duty_u16(0)",
      "    sleep(0.08)",
      "",
      "buzzer.deinit()",
    ].join("\n"),
    expected: "낮은 음에서 높은 음으로 올라가는 세 개의 짧은 소리가 재생된 뒤 멈춥니다.",
    challenge: "온도가 임계값을 넘었을 때만 두 번의 경고음이 울리도록 7차시 코드와 결합하세요.",
    errors: [
      { symptom: "소리가 계속 남", cause: "duty_u16(0) 또는 deinit() 누락", fix: "각 음 뒤 duty를 0으로 하고 마지막에 deinit" },
      { symptom: "딸깍 소리만 남", cause: "능동·수동 부저 혼동 또는 주파수 누락", fix: "수동 부저 확인 후 freq() 설정" },
    ],
    quiz: {
      question: "PWM 주파수를 높이면 수동 부저의 소리는 일반적으로 어떻게 되는가?",
      options: ["더 낮아진다", "더 높아진다", "무조건 커진다", "항상 꺼진다"],
      answer: 1,
      explanation: "주파수는 1초 동안의 진동 횟수이므로 커질수록 음높이가 높아집니다.",
    },
    teacher: "음량을 크게 하는 활동보다 주파수·듀티비·시간이 출력을 어떻게 바꾸는지 비교하게 합니다. 교실에서는 짧고 낮은 듀티비를 사용합니다.",
    exam: "freq와 duty_u16의 역할을 바꾸어 설명한 선택지를 구분하게 합니다.",
  },
  {
    id: 10,
    phase: "연결 프로젝트",
    title: "스마트 환경 알림 장치",
    subtitle: "입력·처리·빛·소리를 하나의 작품으로 완성해요",
    duration: "50분",
    icon: GraduationCap,
    objectives: [
      "문제를 입력·처리·출력 단계로 분해할 수 있다.",
      "센서·NeoPixel·부저 코드를 통합할 수 있다.",
      "테스트 결과로 임계값과 출력 방식을 개선할 수 있다.",
    ],
    concepts: [
      { title: "문제 정의", body: "누가 어떤 상황에서 불편한지 정해야 필요한 기능을 고를 수 있습니다." },
      { title: "프로토타입", body: "핵심 기능이 작동하는 첫 모델을 만들고 테스트하며 개선합니다." },
      { title: "통합", body: "각 부품을 따로 시험한 뒤 하나씩 결합해야 오류 원인을 찾기 쉽습니다." },
      { title: "평가", body: "기능뿐 아니라 문제 해결의 타당성, 코드 설명, 테스트 기록을 함께 봅니다." },
    ],
    parts: ["Pico H", "DHT11", "WS2812B 16-LED 링", "수동 부저", "점퍼선", "브레드보드"],
    wiring: [
      { from: "DHT11 DATA", to: "GP22", note: "센서 입력" },
      { from: "NeoPixel DIN", to: "GP0", note: "빛 출력" },
      { from: "수동 부저 +", to: "GP16", note: "PWM 소리 출력" },
      { from: "모든 GND", to: "Pico GND", note: "공통 접지" },
    ],
    steps: [
      "해결할 교실 환경 문제와 사용자를 한 문장으로 정의한다.",
      "입력값·판단 기준·빛·소리 출력을 표로 설계한다.",
      "DHT11, NeoPixel, 부저를 각각 시험한 뒤 결합한다.",
      "경계값 아래·같음·위의 세 경우를 테스트한다.",
      "친구의 사용 후기를 받아 한 가지를 개선한다.",
    ],
    code: [
      "from machine import Pin, PWM",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT11(Pin(22))",
      "pixels = NeoPixel(Pin(0), 16)",
      "buzzer = PWM(Pin(16))",
      "limit = 27",
      "",
      "while True:",
      "    sensor.measure()",
      "    temp = sensor.temperature()",
      "    if temp >= limit:",
      "        pixels.fill((35, 0, 0))",
      "        buzzer.freq(392)",
      "        buzzer.duty_u16(10000)",
      "        sleep(0.15)",
      "        buzzer.duty_u16(0)",
      "    else:",
      "        pixels.fill((0, 20, 8))",
      "        buzzer.duty_u16(0)",
      "    pixels.write()",
      "    print('현재 온도:', temp)",
      "    sleep(2)",
    ].join("\n"),
    expected: "온도가 기준 이상이면 빨간 빛과 짧은 알림음, 기준 미만이면 초록빛이 표시됩니다.",
    challenge: "같은 부품을 사용하되 단순 온도 경보가 아닌 새로운 사용자 문제를 정의하고 출력 규칙을 바꾸세요.",
    errors: [
      { symptom: "결합 후 모두 동작하지 않음", cause: "여러 회로·코드를 한 번에 연결", fix: "센서 → LED → 부저 순서로 분리 테스트" },
      { symptom: "기준 근처에서 알림 반복", cause: "하나의 임계값만 사용", fix: "켜지는 기준과 꺼지는 기준을 다르게 두기" },
    ],
    quiz: {
      question: "통합 프로젝트의 가장 바람직한 테스트 순서는?",
      options: ["모든 부품을 연결하고 한 번만 실행", "각 부품을 따로 확인한 뒤 하나씩 결합", "코드를 외운 뒤 배선", "결과가 나오면 원인 기록 생략"],
      answer: 1,
      explanation: "단위 기능을 먼저 확인하고 순서대로 결합하면 오류가 생긴 지점을 좁힐 수 있습니다.",
    },
    teacher: "완성품의 화려함보다 문제 정의 → 기능 분해 → 단위 테스트 → 통합 → 개선 과정을 평가합니다. 기본 코드를 작동시키고 확장은 수행평가로 이어갑니다.",
    exam: "통합 코드에서 센서 입력·조건 처리·액추에이터 출력을 표시하고 특정 입력의 실행 결과를 서술하게 합니다.",
  },
];

export const phaseColors: Record<string, string> = {
  "AI 맛보기": "bg-violet-50 text-violet-700 ring-violet-200",
  "기초 제어": "bg-blue-50 text-blue-700 ring-blue-200",
  "빛 출력": "bg-amber-50 text-amber-700 ring-amber-200",
  "미디어 아트": "bg-pink-50 text-pink-700 ring-pink-200",
  "센서 입력": "bg-orange-50 text-orange-700 ring-orange-200",
  "자동 제어": "bg-emerald-50 text-emerald-700 ring-emerald-200",
  "아날로그 입력": "bg-red-50 text-red-700 ring-red-200",
  "소리 출력": "bg-indigo-50 text-indigo-700 ring-indigo-200",
  "연결 프로젝트": "bg-teal-50 text-teal-700 ring-teal-200",
};
