export type WokwiLesson = {
  projectUrl: string;
  virtualPart: string;
  realPart: string;
  substitute: string;
  wiring: { part: string; pico: string; note: string }[];
  steps: string[];
  code: string;
  expected: string;
  interaction: string;
  teacherTip: string;
};

export const wokwiLessons: Record<number, WokwiLesson> = {
  1: {
    projectUrl: "https://wokwi.com/projects/473608152413154305",
    virtualPart: "Raspberry Pi Pico의 내장 LED",
    realPart: "Pico H 내장 LED",
    substitute: "대체 부품 없음 · 가상 장치와 실제 장치 모두 GP25 사용",
    wiring: [{ part: "내장 LED", pico: "GP25", note: "외부 배선이 필요하지 않습니다." }],
    steps: [
      "Wokwi 전체 화면을 열고 main.py 탭을 선택한다.",
      "아래 가상 실습 코드를 복사해 기존 코드를 모두 바꾼다.",
      "초록색 ▶ 버튼을 눌러 시뮬레이션을 시작한다.",
      "내장 LED와 시리얼 모니터의 문장을 함께 확인한다.",
    ],
    code: [
      "from machine import Pin",
      "",
      "led = Pin(25, Pin.OUT)",
      "led.value(1)",
      "print('Pico의 첫 출력: LED ON')",
    ].join("\n"),
    expected: "가상 Pico의 내장 LED가 켜지고 시리얼 모니터에 LED ON 문장이 표시됩니다.",
    interaction: "led.value(1)을 led.value(0)으로 바꿔 다시 실행해 보세요.",
    teacherTip: "첫 차시는 회로를 추가하지 않고 실행·중지·코드 수정 세 동작만 익히게 합니다.",
  },
  2: {
    projectUrl: "https://wokwi.com/projects/473608216601752577",
    virtualPart: "Raspberry Pi Pico의 내장 LED",
    realPart: "Pico H 내장 LED",
    substitute: "대체 부품 없음 · 교과서와 같은 GP25 내장 LED",
    wiring: [{ part: "내장 LED", pico: "GP25", note: "외부 배선이 필요하지 않습니다." }],
    steps: [
      "Wokwi 전체 화면을 열고 main.py에 아래 코드를 붙여 넣는다.",
      "▶ 버튼을 눌러 LED의 켜짐과 꺼짐을 관찰한다.",
      "sleep(0.5)를 0.1로 바꾸고 다시 실행한다.",
      "0.5초와 0.1초 패턴의 차이를 학습지에 적는다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "",
      "led = Pin(25, Pin.OUT)",
      "",
      "while True:",
      "    led.on()",
      "    sleep(0.5)",
      "    led.off()",
      "    sleep(0.5)",
    ].join("\n"),
    expected: "내장 LED가 0.5초 간격으로 계속 깜빡입니다.",
    interaction: "sleep 값을 0.1, 1, 2로 차례로 바꾸고 체감 속도를 비교하세요.",
    teacherTip: "실행 전에 한 주기의 총 시간이 1초임을 예측하게 하면 순차 구조가 선명해집니다.",
  },
  3: {
    projectUrl: "https://wokwi.com/projects/473608227916939265",
    virtualPart: "Raspberry Pi Pico의 내장 LED",
    realPart: "Pico H 내장 LED",
    substitute: "대체 부품 없음 · 변수와 반복 횟수에 집중",
    wiring: [{ part: "내장 LED", pico: "GP25", note: "외부 배선이 필요하지 않습니다." }],
    steps: [
      "main.py에 아래 코드를 붙여 넣고 count와 blink_time을 찾는다.",
      "실행 전에 LED가 몇 번 깜빡일지 예상한다.",
      "▶ 버튼을 눌러 LED와 시리얼 모니터를 함께 관찰한다.",
      "count를 5로 바꾸고 예상과 결과가 같은지 확인한다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "",
      "led = Pin(25, Pin.OUT)",
      "blink_time = 0.2",
      "count = 3",
      "",
      "for i in range(count):",
      "    led.on()",
      "    sleep(blink_time)",
      "    led.off()",
      "    sleep(blink_time)",
      "    print(i + 1, '번째 신호')",
    ].join("\n"),
    expected: "LED가 세 번 깜빡이고 모니터에 1~3번째 신호가 출력됩니다.",
    interaction: "count만 5로 바꾸었을 때 코드의 어느 부분까지 영향을 받는지 표시하세요.",
    teacherTip: "range(3)의 값은 0·1·2지만 실행 횟수는 세 번이라는 점을 출력으로 확인시킵니다.",
  },
  4: {
    projectUrl: "https://wokwi.com/projects/473608240900412417",
    virtualPart: "Wokwi NeoPixel 링/스트립의 첫 4픽셀",
    realPart: "WS2812B 8-LED 스틱의 첫 4개",
    substitute: "가상 부품의 모양은 달라도 데이터 핀과 RGB 제어 원리는 같습니다.",
    wiring: [
      { part: "NeoPixel DIN", pico: "GP0", note: "데이터 입력 방향을 확인합니다." },
      { part: "NeoPixel VCC", pico: "VBUS/5V", note: "가상 회로에서는 5V 핀을 사용합니다." },
      { part: "NeoPixel GND", pico: "GND", note: "Pico와 공통 접지합니다." },
    ],
    steps: [
      "Wokwi에서 + 버튼을 눌러 NeoPixel 링 또는 스트립을 추가한다.",
      "DIN→GP0, VCC→5V, GND→GND로 선을 연결한다.",
      "main.py에 아래 코드를 붙여 넣고 ▶ 버튼을 누른다.",
      "RGB 값을 바꾸어 빨강·초록·파랑을 각각 확인한다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "",
      "pixels = NeoPixel(Pin(0), 4)",
      "colors = [(30, 0, 0), (0, 30, 0), (0, 0, 30)]",
      "",
      "for color in colors:",
      "    pixels.fill(color)",
      "    pixels.write()",
      "    sleep(1)",
      "",
      "pixels.fill((0, 0, 0))",
      "pixels.write()",
    ].join("\n"),
    expected: "첫 4개의 가상 LED가 빨강·초록·파랑 순서로 바뀐 뒤 꺼집니다.",
    interaction: "RGB의 각 값을 30 이하로 두고 두 색을 섞어 새로운 색을 만드세요.",
    teacherTip: "실물 스틱은 8개지만 교과서 기본 코드는 첫 4개만 사용한다는 점을 먼저 안내합니다.",
  },
  5: {
    projectUrl: "https://wokwi.com/projects/473608253025098753",
    virtualPart: "Wokwi 16-pixel NeoPixel Ring",
    realPart: "WS2812B 16-LED 링(SZH-LD083)",
    substitute: "가상 링과 실물 링의 LED 수를 모두 16으로 맞춥니다.",
    wiring: [
      { part: "NeoPixel DIN", pico: "GP0", note: "링의 IN 쪽 데이터 핀입니다." },
      { part: "NeoPixel VCC", pico: "VBUS/5V", note: "밝기는 낮게 시작합니다." },
      { part: "NeoPixel GND", pico: "GND", note: "공통 접지합니다." },
    ],
    steps: [
      "Wokwi에서 NeoPixel Ring을 추가하고 pixels 속성을 16으로 맞춘다.",
      "DIN→GP0, VCC→5V, GND→GND로 연결한다.",
      "아래 코드를 실행해 빛 한 점의 이동을 관찰한다.",
      "색·속도·이동 방향 중 하나를 바꾸어 작품 의도를 설명한다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "",
      "pixels = NeoPixel(Pin(0), 16)",
      "colors = [(30, 0, 8), (20, 8, 0), (0, 12, 30)]",
      "",
      "while True:",
      "    for color in colors:",
      "        for i in range(16):",
      "            pixels.fill((0, 0, 0))",
      "            pixels[i] = color",
      "            pixels.write()",
      "            sleep(0.08)",
    ].join("\n"),
    expected: "분홍·주황·파랑 계열의 빛 한 점이 16개의 가상 LED를 따라 이동합니다.",
    interaction: "range(15, -1, -1)을 이용해 반대 방향 이동을 추가해 보세요.",
    teacherTip: "코드를 작품으로 설명할 때 색·속도·방향 중 최소 두 요소에 이유를 붙이게 합니다.",
  },
  6: {
    projectUrl: "https://wokwi.com/projects/473608307655924737",
    virtualPart: "Wokwi DHT22 온습도 센서",
    realPart: "DHT11 모듈(SZH-EK024)",
    substitute: "Wokwi에는 DHT11 대신 DHT22를 사용합니다. 가상 코드는 DHT22, 실물 코드는 DHT11입니다.",
    wiring: [
      { part: "DHT22 VCC", pico: "3V3", note: "가상 센서 전원" },
      { part: "DHT22 SDA", pico: "GP22", note: "실물 DHT11 DATA도 GP22" },
      { part: "DHT22 GND", pico: "GND", note: "공통 접지" },
    ],
    steps: [
      "Wokwi에서 DHT22를 추가하고 VCC·SDA·GND를 표대로 연결한다.",
      "main.py에 아래 DHT22용 코드를 붙여 넣고 실행한다.",
      "센서를 클릭해 온도와 습도 슬라이더를 움직인다.",
      "시리얼 모니터 값이 약 2초마다 바뀌는지 확인한다.",
    ],
    code: [
      "from machine import Pin",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT22(Pin(22))",
      "",
      "while True:",
      "    sensor.measure()",
      "    print('온도:', sensor.temperature(), '°C')",
      "    print('습도:', sensor.humidity(), '%')",
      "    sleep(2)",
    ].join("\n"),
    expected: "설정한 가상 온도와 습도가 시리얼 모니터에 2초마다 표시됩니다.",
    interaction: "센서를 클릭해 온도를 23°C와 29°C로 바꾸고 출력값을 비교하세요.",
    teacherTip: "실물로 옮길 때 DHT22를 DHT11로 바꾸는 한 줄을 학생이 직접 찾게 합니다.",
  },
  7: {
    projectUrl: "https://wokwi.com/projects/473608322324459521",
    virtualPart: "DHT22 + NeoPixel 4픽셀",
    realPart: "DHT11 + WS2812B 스틱의 첫 4개",
    substitute: "가상 DHT22를 실물에서는 DHT11로 바꿉니다. 핀은 GP22로 유지합니다.",
    wiring: [
      { part: "DHT22 SDA", pico: "GP22", note: "VCC는 3V3, GND는 공통" },
      { part: "NeoPixel DIN", pico: "GP0", note: "VCC는 VBUS/5V, GND는 공통" },
      { part: "두 부품 GND", pico: "GND", note: "모든 장치가 기준 전압을 공유" },
    ],
    steps: [
      "DHT22와 NeoPixel을 추가해 표의 핀으로 각각 연결한다.",
      "아래 코드를 실행하고 현재 온도의 예상 색을 말한다.",
      "DHT22를 클릭해 온도를 26°C와 28°C로 바꾼다.",
      "임계값 27에서 색이 바뀌는 이유를 조건문으로 설명한다.",
    ],
    code: [
      "from machine import Pin",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT22(Pin(22))",
      "pixels = NeoPixel(Pin(0), 4)",
      "",
      "while True:",
      "    sensor.measure()",
      "    temp = sensor.temperature()",
      "    color = (35, 0, 0) if temp >= 27 else (0, 12, 30)",
      "    pixels.fill(color)",
      "    pixels.write()",
      "    print(temp, '°C')",
      "    sleep(2)",
    ].join("\n"),
    expected: "27°C 이상은 빨간색, 미만은 파란색으로 4개의 LED가 바뀝니다.",
    interaction: "가상 온도를 26, 27, 28°C로 바꾸고 참/거짓 결과표를 만드세요.",
    teacherTip: "가상 센서 슬라이더로 경계값 아래·같음·위를 빠르게 반복 실험하게 합니다.",
  },
  8: {
    projectUrl: "https://wokwi.com/projects/473608342726604801",
    virtualPart: "Wokwi Potentiometer(가변저항)",
    realPart: "아날로그 Pulse Sensor 호환 모듈(SZH-HWS008)",
    substitute: "Wokwi에는 Pulse Sensor 대신 가변저항을 사용합니다. 둘 다 GP28의 연속적인 아날로그 값을 만듭니다.",
    wiring: [
      { part: "Potentiometer VCC", pico: "3V3", note: "가상 입력 장치 전원" },
      { part: "Potentiometer SIG", pico: "GP28 / ADC2", note: "실물 센서 S 핀과 동일" },
      { part: "Potentiometer GND", pico: "GND", note: "공통 접지" },
    ],
    steps: [
      "Wokwi에서 Potentiometer를 추가하고 VCC·SIG·GND를 연결한다.",
      "아래 ADC 코드를 실행해 숫자와 막대를 관찰한다.",
      "가변저항 손잡이를 천천히 왼쪽·가운데·오른쪽으로 움직인다.",
      "각 위치의 값 범위를 기록하고 아날로그 입력의 연속성을 설명한다.",
    ],
    code: [
      "from machine import ADC, Pin",
      "from time import sleep",
      "",
      "signal = ADC(Pin(28))",
      "",
      "while True:",
      "    value = signal.read_u16()",
      "    bars = value // 4000",
      "    print(value, '|' + '■' * bars)",
      "    sleep(0.05)",
    ].join("\n"),
    expected: "가변저항을 돌리면 0~65535 범위의 값과 막대 길이가 연속적으로 바뀝니다.",
    interaction: "손잡이를 세 위치에 두고 최솟값·중간값·최댓값을 표로 기록하세요.",
    teacherTip: "이 차시는 ADC 원리 관찰용이며 실제 센서값은 의료 진단이나 개인 비교에 사용하지 않습니다.",
  },
  9: {
    projectUrl: "https://wokwi.com/projects/473608358068325377",
    virtualPart: "Wokwi Buzzer",
    realPart: "수동 부저(ONE010)",
    substitute: "가상 부저와 실물 수동 부저 모두 GP16 PWM으로 제어합니다.",
    wiring: [
      { part: "Buzzer +", pico: "GP16", note: "PWM 출력" },
      { part: "Buzzer -", pico: "GND", note: "공통 접지" },
    ],
    steps: [
      "Wokwi에서 Buzzer를 추가하고 +를 GP16, -를 GND에 연결한다.",
      "아래 코드를 붙여 넣고 음량을 낮춘 상태에서 실행한다.",
      "262·330·392Hz의 음높이를 비교한다.",
      "두 주파수와 쉬는 시간을 조합해 짧은 알림을 만든다.",
    ],
    code: [
      "from machine import Pin, PWM",
      "from time import sleep",
      "",
      "buzzer = PWM(Pin(16))",
      "notes = [262, 330, 392]",
      "",
      "for note in notes:",
      "    buzzer.freq(note)",
      "    buzzer.duty_u16(12000)",
      "    sleep(0.25)",
      "    buzzer.duty_u16(0)",
      "    sleep(0.08)",
      "",
      "buzzer.deinit()",
    ].join("\n"),
    expected: "낮은 음에서 높은 음으로 올라가는 세 개의 짧은 소리가 난 뒤 멈춥니다.",
    interaction: "가상 실행 중 소리가 크면 기기의 음량을 낮추고, 주파수만 바꾸어 높이를 비교하세요.",
    teacherTip: "교실에서는 duty 값을 낮게, 소리는 짧게 사용하도록 시작 전에 기준을 정합니다.",
  },
  10: {
    projectUrl: "https://wokwi.com/projects/473608372770415617",
    virtualPart: "DHT22 + 16 NeoPixel Ring + Buzzer",
    realPart: "DHT11 + 16-LED 링 + 수동 부저",
    substitute: "가상 DHT22만 실물 DHT11로 바꾸고 GP22·GP0·GP16 핀 구성은 유지합니다.",
    wiring: [
      { part: "DHT22 SDA", pico: "GP22", note: "VCC는 3V3" },
      { part: "NeoPixel DIN", pico: "GP0", note: "VCC는 VBUS/5V" },
      { part: "Buzzer +", pico: "GP16", note: "PWM 출력" },
      { part: "모든 GND", pico: "GND", note: "공통 접지" },
    ],
    steps: [
      "세 부품을 한 번에 연결하지 말고 DHT22→링→부저 순서로 추가한다.",
      "각 부품의 단독 동작을 확인한 뒤 아래 통합 코드를 실행한다.",
      "온도를 26·27·28°C로 바꾸어 빛과 소리 결과를 기록한다.",
      "알림 기준 또는 출력 색을 바꾸고 해결하려는 문제와 연결한다.",
    ],
    code: [
      "from machine import Pin, PWM",
      "from neopixel import NeoPixel",
      "from time import sleep",
      "import dht",
      "",
      "sensor = dht.DHT22(Pin(22))",
      "pixels = NeoPixel(Pin(0), 16)",
      "buzzer = PWM(Pin(16))",
      "limit = 27",
      "",
      "while True:",
      "    sensor.measure()",
      "    temp = sensor.temperature()",
      "    if temp >= limit:",
      "        pixels.fill((35, 0, 0))",
      "        buzzer.freq(392)",
      "        buzzer.duty_u16(10000)",
      "        sleep(0.15)",
      "        buzzer.duty_u16(0)",
      "    else:",
      "        pixels.fill((0, 20, 8))",
      "        buzzer.duty_u16(0)",
      "    pixels.write()",
      "    print('현재 온도:', temp)",
      "    sleep(2)",
    ].join("\n"),
    expected: "27°C 이상이면 16개의 빨간 빛과 짧은 알림음, 미만이면 초록빛이 표시됩니다.",
    interaction: "경계값 아래·같음·위의 세 경우를 모두 시험한 뒤 한 가지 규칙을 개선하세요.",
    teacherTip: "기능 완성도뿐 아니라 단위 테스트 기록과 개선 이유를 함께 평가합니다.",
  },
};
